# Generated by Django 5.2 on 2025-04-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='moradia_tipo',
            new_name='tipo_moradia',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='idade',
            field=models.IntegerField(editable=False),
        ),
    ]
