# Generated by Django 5.2 on 2025-04-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_moradia_tipo_candidato_tipo_moradia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel_nome', models.CharField(blank=True, max_length=200)),
                ('responsavel_data_nascimento', models.DateField(blank=True, null=True)),
                ('responsavel_idade', models.IntegerField(blank=True, null=True)),
                ('responsavel_sexo', models.CharField(blank=True, max_length=20)),
                ('responsavel_raca_cor', models.CharField(blank=True, max_length=50)),
                ('responsavel_cpf', models.CharField(blank=True, max_length=14)),
                ('responsavel_telefone', models.CharField(blank=True, max_length=20)),
                ('responsavel_whatsapp', models.BooleanField(default=False)),
                ('responsavel_estado_civil', models.CharField(blank=True, max_length=50)),
                ('responsavel_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='responsavel_cpf',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='responsavel_data_nascimento',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='responsavel_email',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='responsavel_estado_civil',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='responsavel_idade',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='responsavel_nome',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='responsavel_raca_cor',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='responsavel_sexo',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='responsavel_telefone',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='responsavel_whatsapp',
        ),
    ]
