# Generated by Django 5.2 on 2025-04-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_responsavel_remove_candidato_responsavel_cpf_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aluno",
            old_name="Candidato",
            new_name="candidato",
        ),
    ]
