# Generated by Django 5.2 on 2025-04-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_rename_candidato_aluno_candidato"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="senha",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
