# Generated by Django 5.2 on 2025-04-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_candidato_aprovado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidato",
            name="aprovado",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
