# Generated by Django 5.2 on 2025-04-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_candidato_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='senha',
        ),
    ]
