# Generated by Django 5.2 on 2025-04-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0012_eventocalendario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("data", models.DateField()),
                ("hora", models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
