# Generated by Django 5.2 on 2025-05-02 03:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0016_remove_aluno_professor_mensagemchat_delete_mensagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="codigo",
            field=models.CharField(default="DEFAULT001", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="turma",
            name="data_criacao",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="turma",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ConteudoTurma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "arquivo",
                    models.FileField(blank=True, null=True, upload_to="conteudos/"),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conteudos",
                        to="portal.turma",
                    ),
                ),
            ],
        ),
    ]
