# Generated by Django 5.2 on 2025-05-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0017_turma_codigo_turma_data_criacao_turma_descricao_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aviso",
            old_name="autor",
            new_name="criado_por",
        ),
        migrations.AlterField(
            model_name="aviso",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
    ]
