# Generated by Django 5.1.7 on 2025-05-08 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_rename_autor_aviso_criado_por_alter_aviso_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(related_name='turmas', to=settings.AUTH_USER_MODEL),
        ),
    ]
