# Generated by Django 5.1.1 on 2025-05-13 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_horarioaula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='horario',
        ),
        migrations.CreateModel(
            name='HorarioTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='portal.turma')),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('turma', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
