# Generated by Django 5.1.1 on 2025-05-13 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_remove_turma_horario_horarioturma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioturma',
            options={'ordering': ['hora_inicio']},
        ),
        migrations.AlterUniqueTogether(
            name='horarioturma',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='horarioturma',
            name='dia_semana',
        ),
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')])),
                ('horario_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='portal.horarioturma')),
            ],
            options={
                'unique_together': {('dia', 'horario_turma')},
            },
        ),
    ]
