# Generated by Django 5.2.1 on 2025-05-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_turma_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioaula',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
