# Generated by Django 5.2.1 on 2025-05-16 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0023_horarioaula_horario_fim"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaAula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dias_aula",
                        to="portal.turma",
                    ),
                ),
            ],
            options={
                "ordering": ["data"],
                "unique_together": {("turma", "data")},
            },
        ),
        migrations.CreateModel(
            name="Presenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presente", models.BooleanField(default=False)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.aluno"
                    ),
                ),
                (
                    "dia_aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.diaaula"
                    ),
                ),
            ],
            options={
                "unique_together": {("aluno", "dia_aula")},
            },
        ),
    ]
